AWSTemplateFormatVersion: 2010-09-09
Description: Contains all the resources necessary for a single dataset

Parameters:
  pAnalyticsBucket:
    Description: The analytics bucket for the solution
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/AnalyticsBucket
  pApp:
    Description: Name of the application
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Misc/pApp
  pCentralBucket:
    Description: The central bucket for the solution
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/CentralBucket
  pDatasetName:
    Description: The name of the dataset (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]{2,14}"
  pEnvironment:
    Description: Environment name
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Misc/pEnv
  pOrg:
    Description: Name of the organization owning the datalake
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Misc/pOrg
  pPipelineBucket:
    Description: The artifactory bucket used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/ArtifactsBucket
  pPipelineName:
    Description: The name of the pipeline (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]*"
  pStageBucket:
    Description: The stage bucket for the solution
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/StageBucket
  pTeamName:
    Description: Name of the team owning the pipeline (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]*"

Resources:
  ######## TRIGGERS #########
  rTriggerStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sdlf-${pTeamName}-${pPipelineName}-${pDatasetName}-sm-trigger
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub sdlf-${pTeamName}-${pPipelineName}-${pDatasetName}-statemachine-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource:
                  - !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sdlf-${pTeamName}-${pPipelineName}-*
      Path: /state-machine/

  rStateRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sdlf-${pTeamName}-${pDatasetName}-rule-a
      Description: Trigger StageA State Machine every 5 minutes
      State: ENABLED
      ScheduleExpression: cron(*/5 * * * ? *)
      Targets:
        - Id: !Sub sdlf-${pTeamName}-${pDatasetName}-rule-a
          Arn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sdlf-${pTeamName}-${pPipelineName}-sm-a
          Input: !Sub |
            {
              "body": {
                "bucket": "${pCentralBucket}",
                "team": "${pTeamName}",
                "pipeline": "${pPipelineName}",
                "pipeline_stage": "StageA",
                "dataset": "${pDatasetName}",
                "env": "${pEnvironment}",
                "dependent_stage": "StageB",
                "retry_count": 2
              }
            }
          RoleArn: !GetAtt rTriggerStateMachineRole.Arn