AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Resources to be created by the common stack"

Parameters:
  pKMSKeyId:
    Type: String

Resources:
  ######## DYNAMODB #########
  rDynamoWrkLoadManagement:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "workload-management-ddb"
      SSESpecification:
        SSEEnabled: True
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

Outputs:
  oddb:
    Description: "Arn of the KMS key"
    Value: !Ref rDynamoWrkLoadManagement

  