AWSTemplateFormatVersion: "2010-09-09"
Description: "Engineering Glue Connection"

Parameters:
    pAZ:
      Type: String
      Description: The AvailabilityZone name (i.e. us-east-1a).
    pSecurityGroupA:
      Type: String
      Description: The SecurityGroup Id (i.e. sg-02b4b7467bfe3b6fa).
    pSecurityGroupB:
      Type: String
      Description: The SecurityGroup Id (i.e. sg-02b4b7467bfe3b6fa).
    pSubnetId:
      Type: String
      Description: The Subnet Id (i.e. subnet-01fe9be9f1e2f7def).

Resources:
  connection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        ConnectionProperties: {}
        ConnectionType: NETWORK
        Description: "network connected to the on premises data source"
        Name: !Sub 'sdlf-engineering-glue-conn'
        PhysicalConnectionRequirements:
          AvailabilityZone: !Sub '${pAZ}'
          SecurityGroupIdList:
            - !Sub '${pSecurityGroupA}'
            - !Sub '${pSecurityGroupB}'
          SubnetId: !Sub '${pSubnetId}'